spring.application.name=edgeserver
server.port=8087
spring.web.error.include-message=always
app.eureka-username=u
app.eureka-password=p
app.eureka-server=eureka
app.auth-server=auth-server
eureka.client.serviceUrl.defaultZone=http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
eureka.client.initialInstanceInfoReplicationIntervalSeconds=5
eureka.client.registryFetchIntervalSeconds=5
eureka.instance.leaseRenewalIntervalInSeconds=5
eureka.instance.leaseExpirationDurationInSeconds=5
spring.cloud.gateway.server.webmvc.routes[0].id=PRODUCER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://PRODUCER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/**
# Expose all endpoints except shutdown
#spring.ssl.bundle.jks.gateway.key.alias=localhost
#spring.ssl.bundle.jks.gateway.keystore.type=PKCS12
#spring.ssl.bundle.jks.gateway.keystore.location=classpath:keystore/edge.p12
#spring.ssl.bundle.jks.gateway.keystore.password=password
#server.ssl.bundle=edgeserver
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${app.auth-server}:9999
management.endpoint.gateway.enabled=true
management.endpoint.health.show-details=ALWAYS
management.endpoints.web.exposure.include=*
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web.server.adapter.HttpWebHandlerAdapter=TRACE