spring.application.name=edgeserver
server.port=8087
spring.web.error.include-message=always
app.eureka-server=localhost
eureka.client.serviceUrl.defaultZone=http://${app.eureka-server}:8761/eureka/
eureka.client.initialInstanceInfoReplicationIntervalSeconds=5
eureka.client.registryFetchIntervalSeconds=5
eureka.instance.leaseRenewalIntervalInSeconds=5
eureka.instance.leaseExpirationDurationInSeconds=5
spring.cloud.gateway.server.webmvc.routes[0].id=PRODUCER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://PRODUCER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/**
# Expose all endpoints except shutdown
management.endpoints.web.exposure.include=*