spring.application.name=batch
schemaName=db
tableName=Person
dbColumns=firstName,lastName,active,email
filePath=
allHeadersFromFile=firstName,lastName,age,active,email
fileName=
fileExtension=
delimiter=
