spring.application.name=producer-service
server.port=9090
spring.web.error.include-message=always
app.eureka-server=localhost
eureka.client.serviceUrl.defaultZone=http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
eureka.client.initialInstanceInfoReplicationIntervalSeconds=5
eureka.client.registryFetchIntervalSeconds=5
eureka.instance.leaseRenewalIntervalInSeconds=5
eureka.instance.leaseExpirationDurationInSeconds=5
app.eureka-username=u
app.eureka-password=p
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${app.auth-server}:9999
management.endpoint.health.show-details=ALWAYS
management.endpoints.web.exposure.include=*
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web.server.adapter.HttpWebHandlerAdapter=TRACE

#http://localhost:9090/hello

