spring.application.name=producer-service
server.port=9090
spring.web.error.include-message=always
app.eureka-server=localhost
eureka.client.serviceUrl.defaultZone=http://${app.eureka-server}:8761/eureka/
eureka.client.initialInstanceInfoReplicationIntervalSeconds=5
eureka.client.registryFetchIntervalSeconds=5
eureka.instance.leaseRenewalIntervalInSeconds=5
eureka.instance.leaseExpirationDurationInSeconds=5




